# Gross Domestic Product (GDP) growth rate - Data Cleaning 

### Data Info:
* **Indicator:** `Real GDP growth rate (yoy)`
* **Source:** National Anti-Corruption Bureau of Ukraine: https://nabu.ua/ua/vvp-2.html 
* **Raw File:** `data_raw/GDP.xlsx`
* **Output:** `data_processed/GDP_clean.xlsx`  

### Cleaning Notes:
- source file contains multi-row headers and merged cells

In [1]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\admin\anaconda3\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
file_path = Path("../../data_raw/GDP.xls")
output_path = Path("../../data_processed/GDP_clean.xlsx")
output_path.parent.mkdir(parents=True, exist_ok=True)

sheet_name = "Sheet1 "

df_raw = pd.read_excel(file_path, sheet_name=sheet_name, header=None)
df_raw.head()

,0,1,2,3,4,5,6,7,8,9,...,165,166,167,168,169,170,171,172,173,174
0,Дата,NaN,Валовий внутрішній продукт,NaN,NaN,NaN,NaN,NaN,В розрізі галузей виробництва,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Внесок окремих компонентів у динаміку ВВП,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Сіліське, лісове та рибне господарство",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,ВДВ,% р/р,% г/г номінальний,% дефл. г/г,% зм. (з коригуванням на сезонність) кв./кв.,в екв. дол. США,ВДВ,% р/р,...,% р/р,% дефл.,% частка,% зм. (CК) кв./кв.,Споживання домогосподарств,Споживання держави,Інвестиції,Торгове сальдо,Експорт,Імпорт

In [4]:
# set correct header, only keep needed columns

df = df_raw.copy()
df = df.iloc[:, [1, 3]].copy()

df.columns = ["date", "value"]
df = df.iloc[5:].copy()

df.head(5)

         date  value
5  1 кв. 2000  0.052
6  2 кв. 2000  0.043
7  3 кв. 2000  0.068
8  4 кв. 2000  0.067
9  1 кв. 2001  0.077

In [5]:
# clean quarter labels
# 1 кв. 2000 -> 2000Q1

df["date"] = (
    df["date"]
    .astype(str)
    .str.strip()
    .str.replace(r"(\d)\s*кв\.\s*(\d{4})", r"\2Q\1", regex=True)
)


df["indicator"] = "gdp_growth"

df["year"] = df["date"].str[:4].astype(int)
df = df[df["year"] >= 2015].copy()
df = df.drop(columns="year")

df.head(10)

      date  value   indicator
65  2015Q1  -0.16  gdp_growth
66  2015Q2 -0.145  gdp_growth
67  2015Q3  -0.07  gdp_growth
68  2015Q4 -0.024  gdp_growth
69  2016Q1  0.001  gdp_growth
70  2016Q2  0.017  gdp_growth
71  2016Q3  0.027  gdp_growth
72  2016Q4  0.046  gdp_growth
73  2017Q1  0.028  gdp_growth
74  2017Q2  0.027  gdp_growth

In [6]:
df.to_excel(output_path, index=False)
print(f"saved to: {output_path}")

saved to: ..\..\data_processed\GDP_clean.xlsx